<?php

?>
<?php
/**
 * @var \MGS\GeoIp\Block\Adminhtml\System\Config\ImportGeoIp $block
 */
?>

<script>
    require([
        'jquery',
        'prototype'
    ], function ($) {
        var collectSpan = $('#import_geoip_process');
        var buttonDownload = $('#import_geoip');
        buttonDownload.click(function () {
            var params = {};
            new Ajax.Request('<?php echo $block->getDownloadAjaxUrl() ?>', {
                parameters: params,
                loaderArea: false,
                asynchronous: true,
                onCreate: function () {
                    collectSpan.find('.collected').hide();
                    collectSpan.find('.processing').show();
                    $('#collect_message_span').text('');
                    buttonDownload.prop("disabled", true);

                },
                beforeSend:function () {
                    console.log("tesststsetwserasdf");
                },
                onSuccess: function (response) {
                    var response = JSON.parse(response.responseText);
                    collectSpan.find('.processing').hide();
                    collectSpan.find('.collected').show();
                    buttonDownload.prop("disabled", false);
                    if (response.success) {
                        $('<div class="message message-success" style="margin-bottom: 5px;color:#79a22e"><p>' + response.message + '</p></div>').insertBefore(buttonDownload);
                        importGeoIp()
                    } else {
                        $('<div class="message message-error" style="margin-bottom: 5px;color:red"><p>' + response.message + '</p></div>').insertBefore(buttonDownload);
                    }
                },
                always: function () {
                    buttonDownload.prop("disabled", false);
                }
            });
        });
        function importGeoIp() {
            var params = {};
            new Ajax.Request('<?php echo  $block->getAjaxUrl() ?>', {
                parameters: params,
                loaderArea: false,
                asynchronous: true,
                onCreate: function () {
                    collectSpan.find('.collected').hide();
                    collectSpan.find('.processing').show();
                    $('#collect_message_span').text('');
                    buttonDownload.prop("disabled", true);
                },

                onSuccess: function (response) {
                    var response = JSON.parse(response.responseText);
                    collectSpan.find('.processing').hide();
                    collectSpan.find('.collected').show();
                    buttonDownload.prop("disabled", false);
                    if (response.success) {
                        $('<div class="message message-success" style="margin-bottom: 5px;color:#79a22e"><p>' + response.message + '</p></div>').insertBefore(buttonDownload);
                    } else {
                        $('<div class="message message-error" style="margin-bottom: 5px;color:red"><p>' + response.message + '</p></div>').insertBefore(buttonDownload);
                    }
                },
                always: function () {
                    buttonDownload.prop("disabled", false);
                }
            });
        }
    });
</script>
<?php echo $block->getButtonHtml() ?>
<span class="collect-indicator" id="import_geoip_process">
	<span class="processing" hidden="hidden">
		<img alt="Collecting" style="margin:0 5px"
             src="<?php echo $block->getViewFileUrl('images/process_spinner.gif') ?>"/>
        <?php echo __('Please wait ...') ?>
	</span>
    <img class="collected"  alt="Collected" style="margin:-3px 5px"
         src="<?php echo $block->getViewFileUrl('images/rule_component_apply.gif') ?>"/>
</span>
