<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2019 Amasty (https://www.amasty.com)
 * @package Amasty_Geoip
 */
?>
<?php
/**
 * @var \Amasty\Geoip\Block\Adminhtml\Settings\Import $this
 */
?>

<form action="#" enctype="multipart/form-data" method="post">
    <div>
    <input type="file" name="file_upload" id="file_upload" multiple>
    </div>
    <div>
    <button id="am-import" class="action-default scalable" data-ui-id="widget-button-0" type="button" title="<?= __('Import') ?>">
        <span><?= __('Import') ?></span>
    </button>
    </div>
</form>

